log_file path=/tmp/rocprof-aggregator.log
log_level level=INFO
pid_file path=/tmp/rocprof-aggregator.pid
set_memory size=512M
daemon_name name=rocm_aggregator

auth_add name=none plugin=none
listen xprt=sock port=10412 auth=none

prdcr_add name=rocm_sampler type=active xprt=sock host=127.0.0.1 port=10411 auth=none reconnect=1s
prdcr_start name=rocm_sampler

updtr_add name=rocm_updater interval=1s push=onchange
updtr_prdcr_add name=rocm_updater regex=rocm_sampler
updtr_start name=rocm_updater

load name=store_csv
config name=store_csv path=/tmp/rocprof-ldms buffer=0 typeheader=1

strgp_add name=pc_csv plugin=store_csv container=pc_sampling schema=rocm_pc_raw_window decomposition=ldms/pc-decomp.json
strgp_prdcr_add name=pc_csv regex=rocm_sampler
strgp_start name=pc_csv

strgp_add name=device_csv plugin=store_csv container=device_counting schema=rocm_device_raw_window decomposition=ldms/device-decomp.json
strgp_prdcr_add name=device_csv regex=rocm_sampler
strgp_start name=device_csv

strgp_add name=trace_csv plugin=store_csv container=tracing schema=rocm_trace_raw_window decomposition=ldms/trace-decomp.json
strgp_prdcr_add name=trace_csv regex=rocm_sampler
strgp_start name=trace_csv
