log_file path=/tmp/rocprof-sampler.log
log_level level=INFO
pid_file path=/tmp/rocprof-sampler.pid
set_memory size=512M
daemon_name name=rocm_sampler

auth_add name=none plugin=none
msg_enable
listen xprt=sock port=10411 auth=none

load name=rocprof_msg_sampler
config name=rocprof_msg_sampler producer=rocm_sampler pc_instance=rocm_sampler/rocm_pc_raw_window device_instance=rocm_sampler/rocm_device_raw_window trace_instance=rocm_sampler/rocm_trace_raw_window max_records=256
start name=rocprof_msg_sampler interval=1000000000 offset=0
